"""add profile resume and job domain tables

Revision ID: a119af425295
Revises: e77d77a9d923
Create Date: 2026-08-01 20:07:02.357176+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a119af425295"
down_revision: str | None = "e77d77a9d923"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_templates",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("company_logo_url", sa.String(length=512), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "location_type",
            sa.Enum(
                "remote", "onsite", "hybrid", name="LocationType", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "freelance",
                name="EmploymentType",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "entry",
                "junior",
                "mid",
                "senior",
                "lead",
                "executive",
                name="ExperienceLevel",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "source",
            sa.Enum("internal", "external", name="JobSource", native_enum=False, length=32),
            server_default="internal",
            nullable=False,
        ),
        sa.Column("external_url", sa.String(length=512), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resumes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "completed", "archived", name="ResumeStatus", native_enum=False, length=32
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "latest_parse_status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "failed",
                name="ParseStatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("last_parsed_at", sa.Date(), nullable=True),
        sa.Column("resume_template_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["resume_template_id"], ["resume_templates.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resumes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_educations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("degree", sa.String(length=255), nullable=True),
        sa.Column("institution", sa.String(length=255), nullable=False),
        sa.Column("field_of_study", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("gpa", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_educations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_educations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_experiences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_experiences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_experiences_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_references",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_references", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_references_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_language", sa.String(length=10), server_default="en", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column(
            "profile_visibility",
            sa.Enum(
                "private",
                "public",
                "contacts_only",
                name="ProfileVisibility",
                native_enum=False,
                length=32,
            ),
            server_default="private",
            nullable=False,
        ),
        sa.Column("notification_preferences", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_settings_user_id"), ["user_id"], unique=True)

    op.create_table(
        "user_skills",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "proficiency_level",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="UserSkillProficiency",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("years_of_experience", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_skills_user_id"), ["user_id"], unique=False)

    op.create_table(
        "applications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "applied",
                "under_review",
                "interviewing",
                "offered",
                "rejected",
                "withdrawn",
                name="ApplicationStatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.Date(), nullable=True),
        sa.Column("last_activity_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("resume_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id", name="uq_applications_user_job"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "generated_resumes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column(
            "generation_status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "failed",
                name="GenerationStatus",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generated_resumes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_resumes_resume_id"), ["resume_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_generated_resumes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "match_results",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("match_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("matched_skills", sa.JSON(), nullable=True),
        sa.Column("missing_skills", sa.JSON(), nullable=True),
        sa.Column("strengths", sa.JSON(), nullable=True),
        sa.Column("weaknesses", sa.JSON(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("match_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_match_results_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_match_results_resume_id"), ["resume_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_match_results_user_id"), ["user_id"], unique=False)

    op.create_table(
        "resume_drafts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "draft_status",
            sa.Enum(
                "in_progress",
                "completed",
                "archived",
                name="DraftStatus",
                native_enum=False,
                length=32,
            ),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_drafts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resume_drafts_resume_id"), ["resume_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_resume_drafts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "uploaded_resumes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "parse_status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "failed",
                name="ParseStatus",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("parsed_data", sa.JSON(), nullable=True),
        sa.Column("parsed_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uploaded_resumes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_uploaded_resumes_resume_id"), ["resume_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_uploaded_resumes_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploaded_resumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploaded_resumes_user_id"))
        batch_op.drop_index(batch_op.f("ix_uploaded_resumes_resume_id"))

    op.drop_table("uploaded_resumes")
    with op.batch_alter_table("resume_drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_drafts_user_id"))
        batch_op.drop_index(batch_op.f("ix_resume_drafts_resume_id"))

    op.drop_table("resume_drafts")
    with op.batch_alter_table("match_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_results_user_id"))
        batch_op.drop_index(batch_op.f("ix_match_results_resume_id"))
        batch_op.drop_index(batch_op.f("ix_match_results_job_id"))

    op.drop_table("match_results")
    with op.batch_alter_table("generated_resumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generated_resumes_user_id"))
        batch_op.drop_index(batch_op.f("ix_generated_resumes_resume_id"))

    op.drop_table("generated_resumes")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_user_id"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))

    op.drop_table("applications")
    with op.batch_alter_table("user_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_skills_user_id"))

    op.drop_table("user_skills")
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_settings_user_id"))

    op.drop_table("user_settings")
    with op.batch_alter_table("user_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_references_user_id"))

    op.drop_table("user_references")
    with op.batch_alter_table("user_experiences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_experiences_user_id"))

    op.drop_table("user_experiences")
    with op.batch_alter_table("user_educations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_educations_user_id"))

    op.drop_table("user_educations")
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resumes_user_id"))

    op.drop_table("resumes")
    op.drop_table("jobs")
    op.drop_table("resume_templates")
    # ### end Alembic commands ###
